#!/usr/bin/env python3
"""
Split video files into segments of a max length and PGP-encrypt each segment,
so they can be played back by the Segment Player web app.

For every directory under the given root that directly contains video files:
  - each video longer than --seconds is split into consecutive
    --seconds-or-less chunks (ffmpeg, re-encoded for frame-accurate cuts —
    a stream-copy split would snap to keyframes and could exceed --seconds)
  - every resulting chunk (or the whole file, if it was already short enough)
    is PGP-encrypted in place with the given public key, as binary OpenPGP
    (<name>.gpg), never touching plaintext once encrypted
  - a playlist.txt is written listing that directory's own .gpg files in
    alphabetical order (which also puts each file's parts in the right
    sequence, since part numbers are zero-padded) — one playlist per
    directory, matching how the web app expects a flat list of segment
    filenames relative to wherever the playlist itself is opened from

Requires ffmpeg + ffprobe on PATH, and the `pgpy` package:
    pip install pgpy

On Python 3.13+, pgpy also needs a backport of the stdlib `imghdr` module
that Python removed:
    pip install standard-imghdr

On Ubuntu/Debian, `./install.sh` sets all of the above up for you (ffmpeg
via apt, and the Python packages into a scripts/.venv virtualenv, since
current Ubuntu releases block plain `pip install` outside one).

Public/private key compatibility: PGPy is most reliable with plain RSA
keys. Elliptic-curve keys (curve25519 etc.) generated by other tools may
hit format quirks — if encryption fails on an ECC key, regenerate an RSA
key pair instead.

The `pubkey` argument accepts either a path to an armored key file, or the
key given directly as a base64 string (e.g. `base64 -w0 pubkey.asc`) —
useful for passing the key as a one-line secret without a file on disk.
"""
import argparse
import base64
import math
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

try:
    import pgpy
    from pgpy.constants import CompressionAlgorithm
except ImportError:
    sys.exit(
        "error: the `pgpy` package is required.\n"
        "  pip install pgpy\n"
        "On Python 3.13+ you'll also need: pip install standard-imghdr"
    )

VIDEO_EXTENSIONS = {".mp4", ".mov", ".m4v", ".webm", ".mkv", ".avi", ".ogv"}
PLAYLIST_NAME = "playlist.txt"


def load_key_material(value: str) -> bytes:
    """Accept either a path to a key file, or the key given directly as
    base64 text — either base64-of-the-armored-text or base64-of-the-raw-
    binary-key-packets, pgpy.PGPKey.from_blob auto-detects either once
    decoded.
    """
    path = Path(value)
    if path.is_file():
        return path.read_bytes()
    try:
        return base64.b64decode(value, validate=True)
    except Exception as e:
        sys.exit(f"error: '{value}' is neither an existing file nor valid base64 ({e})")


def check_ffmpeg():
    missing = [exe for exe in ("ffmpeg", "ffprobe") if shutil.which(exe) is None]
    if missing:
        sys.exit(
            f"error: {' and '.join(missing)} not found on PATH. "
            "Install ffmpeg (https://ffmpeg.org/download.html) and try again."
        )


def probe_duration(path: Path) -> float:
    result = subprocess.run(
        [
            "ffprobe", "-v", "error",
            "-show_entries", "format=duration",
            "-of", "default=noprint_wrappers=1:nokey=1",
            str(path),
        ],
        capture_output=True, text=True, check=True,
    )
    return float(result.stdout.strip())


def split_segments(path: Path, seconds: float, tmp_dir: Path) -> list[Path]:
    """Return a list of file paths for this video's playable chunks.

    If the video is already short enough, returns [path] unchanged (no
    re-encode needed). Otherwise re-encodes --seconds-sized chunks via
    -ss/-t, which (unlike a stream-copy segment split) cuts exactly on
    request instead of snapping to the nearest keyframe.
    """
    duration = probe_duration(path)
    if duration <= seconds:
        return [path]

    count = math.ceil(duration / seconds)
    digits = max(2, len(str(count)))
    outputs = []
    for idx in range(count):
        start = idx * seconds
        out_path = tmp_dir / f"{path.stem}_part{idx + 1:0{digits}d}{path.suffix}"
        subprocess.run(
            [
                "ffmpeg", "-y", "-ss", str(start), "-i", str(path), "-t", str(seconds),
                "-c:v", "libx264", "-preset", "veryfast", "-c:a", "aac",
                str(out_path),
            ],
            capture_output=True, text=True, check=True,
        )
        outputs.append(out_path)
    return outputs


def encrypt_file(pubkey: "pgpy.PGPKey", src: Path, dest: Path) -> None:
    data = src.read_bytes()
    message = pgpy.PGPMessage.new(data, compression=CompressionAlgorithm.Uncompressed)
    encrypted = pubkey.encrypt(message)
    dest.write_bytes(bytes(encrypted))


def process_directory(dir_path: Path, pubkey: "pgpy.PGPKey", seconds: float, delete_originals: bool) -> None:
    video_files = sorted(
        p for p in dir_path.iterdir()
        if p.is_file() and p.suffix.lower() in VIDEO_EXTENSIONS
    )
    if not video_files:
        return

    produced = []
    for video in video_files:
        with tempfile.TemporaryDirectory() as tmp:
            tmp_dir = Path(tmp)
            segments = split_segments(video, seconds, tmp_dir)
            multi = len(segments) > 1
            for seg_path in segments:
                out_name = (seg_path.name if multi else video.name) + ".gpg"
                encrypt_file(pubkey, seg_path, dir_path / out_name)
                produced.append(out_name)
        if delete_originals:
            video.unlink()

    playlist_path = dir_path / PLAYLIST_NAME
    playlist_path.write_text("\n".join(sorted(produced)) + "\n", encoding="utf-8")
    print(f"{dir_path}: {len(produced)} encrypted segment(s) -> {playlist_path.name}")


def main():
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("directory", type=Path, help="root directory of videos to process")
    parser.add_argument(
        "pubkey",
        help="PGP public key: a path to an armored key file, or the key itself as base64 text",
    )
    parser.add_argument("--seconds", type=float, default=5.0, help="max segment length in seconds (default: 5)")
    parser.add_argument(
        "--delete-originals", action="store_true",
        help="delete original plaintext video files after successful encryption (default: keep them alongside)",
    )
    args = parser.parse_args()

    check_ffmpeg()

    if not args.directory.is_dir():
        sys.exit(f"error: {args.directory} is not a directory")

    pubkey, _ = pgpy.PGPKey.from_blob(load_key_material(args.pubkey))

    directories = [args.directory] + sorted(p for p in args.directory.rglob("*") if p.is_dir())
    for dir_path in directories:
        process_directory(dir_path, pubkey, args.seconds, args.delete_originals)


if __name__ == "__main__":
    main()
